### PR TITLE
Install man

### LINKED ISSUE #4: Install man
Add `man` to the container To view and test the man page locally while in the container

### PR DESCRIPTION
**Pull request by diveshuttam**
also add less so as to use it as a pager for man
closes #4

### CODE REVIEW

**Review by dashohoxha — COMMENTED** [review]
Have you tested this?

**Comment by diveshuttam** [comment]
Yes, I tried `ds make` and `ds shell`. `man` was working inside the container. 
Though I am new to docker not sure if I missed something.

**Comment by diveshuttam** [comment]
Oh sorry not tested the buster one let me try this again

**Comment by dashohoxha** [comment]
I remember that man package was installed, but the man command was not
working. This is why I asked.

**Comment by diveshuttam** [comment]
`man` package wasn't installed as I was getting errors like `bin/man` not found or something.
installing man was not working properly initially because the pager installed was `more`. I have installed `less` also in the commit and now it is working properly. 
Also `man egpg` wasn't working as such but `man ./man/egpg.1` worked. 
Also doing `make install` again inside the container made the `man egpg` work.

Tested this for buster as well, man pages are working properly.

**Comment by sourabhtk37** [comment]
We need to have a build system(like Travis CI) for this kind of situations.

**Comment by dashohoxha** [comment]
I have never used Travis CI, and I am not sure we need it for this project.
Maybe Divesh can have a look at it by the end of the project, if there is time available.

**Comment by diveshuttam** [comment]
I have worked with Travis CI earlier and its easy to set up. But as I am running a bit behind my schedule it will be good to look into this towards the end.

**Pull request merged**
